apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  type: NodePort